[versions]
minecraft = "1.20.1"
fabric_mappings = "1.20.1+build.10:v2"
fabric_loader = "0.16.14"

fabric_api = "0.92.6+1.20.1"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_mappings = { module = "net.fabricmc:yarn", version.ref = "fabric_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

#[bundles]
#quilted_fabric_api = ["quilted_fabric_api", "quilted_fabric_api_deprecated"]

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.11-SNAPSHOT" }

